name: Build and Push Webapp

on:
  push:
    branches:
      - main  # Adjust according to your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          path: "./main/"
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: web-app
          path: "./web-app/"
        
      - name: build
        run: |
          pip install pygbag
          make build
          cd .
          ls -R

      
