name: Build and Push Webapp

on:
  push:
    branches:
      - main  # Adjust according to your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pygbag
        run: |
          pip install pygbag
          
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
        
      - name: build and commit
        run: |
          make build
          git add .
          git commit -m "web-app build"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
