name: Build and Push Webapp

on:
  push:
    branches:
      - main  # Adjust according to your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          branch: main
        
      - name: build
        run: |
          pip install pygbag
          make build
          cd .
          ls

      
