name: Build and Push Webapp

on:
  push:
    branches:
      - main  # Adjust according to your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies and build
        run: |
          make build
          
      - name: Copy build files to webapp branch
        run: |
          git checkout main
          git checkout webapp
          git rm -r .
          git checkout main -- src/build
          mv src/build/* .
          git add .
          git commit -m "Update webapp"
          git push origin webapp
